spring:
  application:
    name: shopping-mall
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_mall
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true